name: dsg
description: "Static site generator. Supports markdown, mustache, partials, assets, sass. Webserver included."
homepage: https://github.com/maks/dsg

version: 1.0.2

environment:
  sdk: ">=2.8.0 <3.0.0"

# Add the bin/sitegen.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  dsg:

dependencies:
  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

  validate: ^1.0.0

  args: ^1.4.0
  yaml: ^2.1.0
  path: ^1.0.0
  markdown: ^2.1.5
  reflected_mustache: ^1.0.0
  intl: ^0.16.1
  http_server: ^0.9.0

  system_info: ^0.1.0
  where: ^8.0.0
  
  packages: ^0.4.0

  watcher: ^0.9.7
    
dev_dependencies:
  test: any
  grinder: any

  build_runner: any
  build_test: any
